#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Hyperindex
version:      0.02
version_from: lib/Acme/Hyperindex.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
